"""
Render AI insights as a markdown report artifact.
"""

from __future__ import annotations

from typing import Any


_SECTION_TITLES = {
    "unique_id_patterns": "Unique ID Patterns",
    "key_domain_fields": "Key & Domain Fields",
    "structural_value_patterns": "Structural & Value Patterns",
    "cross_object_patterns": "Cross-Object Patterns",
    "domain_field_assessments": "Domain Field Assessments",
    "hidden_value_relationships": "Hidden Value & Relationships",
    "data_story": "Data Story",
    "quality_assessment": "Quality Assessment",
}


def _format_section_body(value: Any) -> str:
    if value is None:
        return "_No findings._\n"
    if isinstance(value, list):
        if not value:
            return "_No findings._\n"
        lines = []
        for item in value:
            if isinstance(item, dict):
                lines.append("- " + "; ".join(f"{k}: {v}" for k, v in item.items()))
            else:
                lines.append(f"- {item}")
        return "\n".join(lines) + "\n"
    if isinstance(value, dict):
        return "\n".join(f"- **{k}**: {v}" for k, v in value.items()) + "\n"
    return f"{value}\n"


def generate_ai_insights_markdown(ai_insights: dict[str, Any]) -> str:
    """
    Generate the AI Insights markdown file from the canonical insights dict.
    """
    if not ai_insights or not ai_insights.get("enabled"):
        provider = ai_insights.get("provider", "none") if ai_insights else "none"
        err = (ai_insights or {}).get("error", "AI insights not generated")
        return f"# AI Insights\n\n_AI provider `{provider}` did not produce insights._\n\n{err}\n"

    provider = ai_insights.get("provider", "unknown")
    model = ai_insights.get("model") or "default"
    auth_mode = ai_insights.get("auth_mode", "unknown")
    lines = [
        "# AI Insights",
        "",
        f"> Generated by **{provider}** ({auth_mode}) · model: `{model}`",
        "",
        "_AI-generated analysis layered on deterministic profiling. "
        "Verify findings before production decisions._",
        "",
    ]

    sections = ai_insights.get("sections") or {}
    order = [
        "data_story",
        "unique_id_patterns",
        "key_domain_fields",
        "structural_value_patterns",
        "cross_object_patterns",
        "domain_field_assessments",
        "hidden_value_relationships",
        "quality_assessment",
    ]
    for key in order:
        val = sections.get(key) or ai_insights.get(key)
        if val:
            title = _SECTION_TITLES.get(key, key.replace("_", " ").title())
            lines.append(f"## {title}")
            lines.append("")
            lines.append(_format_section_body(val))

    recs = ai_insights.get("recommendations") or []
    if recs:
        lines.append("## Recommendations")
        lines.append("")
        for r in recs:
            if isinstance(r, dict):
                sev = r.get("severity", "low")
                cat = r.get("category", "general")
                action = r.get("action", "")
                lines.append(f"- **[{sev.upper()}]** ({cat}) {action}")
            else:
                lines.append(f"- {r}")
        lines.append("")

    return "\n".join(lines)
